spring:
  datasource:
    url: jdbc:mysql://47.94.157.224:3306/seckill?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: seckill
    password: seckill_pass

pagehelper:
  helper-dialect: mysql # 指定数据库
  reasonable: true # 合理化分页参数
  support-methods-arguments: true # 从查询方法参数中获取分页参数
  params: count=countSql # 从对象中根据属性名获取参数